### ISSUE TITLE
Do you sell & ship the PCBs?

### ISSUE THREAD

**Issue by romanhaller** [slu4coder/Minimal-UART-CPU-FLASH-Edition#1]
I recently finished the Ben Eater 8-Bit-Computer. Your project seems like a the next step - would very much like to build it. 

I was wondering if you have one or two spare PCBs you would sell & ship? Seems easier than having them custom printed. I am Germany-based, too. If so, how would I contact you?

**Comment by slu4coder** [comment]
Hallo Roman, freut mich, dass du "Minimal UART CPU" interessant findest. Von der aktuellen FLASH Edition habe ich 3 PCBs fertigen lassen, wovon ich eines aufgebaut habe. Falls du also Interesse hast, würde ich dir eines zusenden gegen einen Unkostenbeitrag von 20€ zzgl. Porto. Schreib mir doch mal (email findest du auf meinem YouTube channel slu4).
LG slu4
